batch_size: 4
epochs: 20
lr: 0.0000001

device: cuda:0
num_workers: 2
seed: 1234
use_wandb: False



# Evaluation
model_path: /content/drive/MyDrive/Deep_Learning/multi-label-classification/outputs/2024-08-22/07-54-26/model_best.pt
